---
name: icli
version: 0.4
author:
  - 'Copyright (C) 2010 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>'
abstract: Icinga Command Line Interface
license: unrestricted
build_requires:
  Test::Command: 0
  Test::Compile: 0
  Test::More: 0
  Test::Pod: 0
requires:
  Date::Format: 0
  Getopt::Long: 0
  Term::ANSIColor: 0
  Term::Size: 0
  autodie: 0
  perl: v5.10.0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
